// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyStagePass.Services.Database;

#nullable disable

namespace MyStagePass.Services.Migrations
{
    [DbContext(typeof(MyStagePassDbContext))]
    [Migration("20251104163625_fixedUserFileds")]
    partial class fixedUserFileds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyStagePass.Services.Database.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AdminID");

                    b.HasIndex("UserID");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminID = 1,
                            UserID = 1
                        });
                });

            modelBuilder.Entity("MyStagePass.Services.Database.City", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityID"));

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityID");

                    b.HasIndex("CountryID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityID = 1,
                            CountryID = 1,
                            Name = "Sarajevo"
                        },
                        new
                        {
                            CityID = 2,
                            CountryID = 1,
                            Name = "Banja Luka"
                        },
                        new
                        {
                            CityID = 3,
                            CountryID = 1,
                            Name = "Tuzla"
                        },
                        new
                        {
                            CityID = 4,
                            CountryID = 1,
                            Name = "Zenica"
                        },
                        new
                        {
                            CityID = 5,
                            CountryID = 1,
                            Name = "Mostar"
                        },
                        new
                        {
                            CityID = 6,
                            CountryID = 1,
                            Name = "Bihać"
                        },
                        new
                        {
                            CityID = 7,
                            CountryID = 2,
                            Name = "Zagreb"
                        },
                        new
                        {
                            CityID = 8,
                            CountryID = 2,
                            Name = "Split"
                        },
                        new
                        {
                            CityID = 9,
                            CountryID = 3,
                            Name = "Skoplje"
                        },
                        new
                        {
                            CityID = 10,
                            CountryID = 4,
                            Name = "Podgorica"
                        },
                        new
                        {
                            CityID = 11,
                            CountryID = 4,
                            Name = "Budva"
                        },
                        new
                        {
                            CityID = 12,
                            CountryID = 4,
                            Name = "Ulcinj"
                        },
                        new
                        {
                            CityID = 13,
                            CountryID = 5,
                            Name = "Beograd"
                        },
                        new
                        {
                            CityID = 14,
                            CountryID = 5,
                            Name = "Novi Sad"
                        });
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryID = 1,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            CountryID = 2,
                            Name = "Croatia"
                        },
                        new
                        {
                            CountryID = 3,
                            Name = "North Macedonia"
                        },
                        new
                        {
                            CountryID = 4,
                            Name = "Montenegro"
                        },
                        new
                        {
                            CountryID = 5,
                            Name = "Serbia"
                        });
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CustomerID");

                    b.HasIndex("UserID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            UserID = 2
                        },
                        new
                        {
                            CustomerID = 2,
                            UserID = 3
                        },
                        new
                        {
                            CustomerID = 3,
                            UserID = 4
                        });
                });

            modelBuilder.Entity("MyStagePass.Services.Database.CustomerFavoriteEvent", b =>
                {
                    b.Property<int>("CustomerFavoriteEventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerFavoriteEventID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.HasKey("CustomerFavoriteEventID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("EventID", "CustomerID")
                        .IsUnique();

                    b.ToTable("CustomerFavoriteEvent");

                    b.HasData(
                        new
                        {
                            CustomerFavoriteEventID = 1,
                            CustomerID = 1,
                            EventID = 1
                        },
                        new
                        {
                            CustomerFavoriteEventID = 2,
                            CustomerID = 1,
                            EventID = 2
                        },
                        new
                        {
                            CustomerFavoriteEventID = 3,
                            CustomerID = 2,
                            EventID = 1
                        },
                        new
                        {
                            CustomerFavoriteEventID = 4,
                            CustomerID = 2,
                            EventID = 3
                        });
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int>("PerformerID")
                        .HasColumnType("int");

                    b.Property<float>("RatingAverage")
                        .HasColumnType("real");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<int>("TicketsAvailable")
                        .HasColumnType("int");

                    b.Property<int>("TicketsSold")
                        .HasColumnType("int");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.HasKey("EventID");

                    b.HasIndex("LocationID");

                    b.HasIndex("PerformerID");

                    b.HasIndex("StatusID");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventID = 1,
                            EventDate = new DateTime(2025, 11, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "Rock Concert",
                            LocationID = 1,
                            PerformerID = 1,
                            RatingAverage = 0f,
                            RatingCount = 0,
                            StatusID = 1,
                            TicketsAvailable = 200,
                            TicketsSold = 50,
                            TotalScore = 0
                        },
                        new
                        {
                            EventID = 2,
                            EventDate = new DateTime(2025, 11, 15, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "Jazz Night",
                            LocationID = 1,
                            PerformerID = 2,
                            RatingAverage = 0f,
                            RatingCount = 0,
                            StatusID = 1,
                            TicketsAvailable = 100,
                            TicketsSold = 30,
                            TotalScore = 0
                        },
                        new
                        {
                            EventID = 3,
                            Description = "Outdoor pop music festival",
                            EventDate = new DateTime(2025, 12, 20, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "Pop Festival",
                            LocationID = 3,
                            PerformerID = 3,
                            RatingAverage = 0f,
                            RatingCount = 0,
                            StatusID = 1,
                            TicketsAvailable = 1000,
                            TicketsSold = 300,
                            TotalScore = 0
                        },
                        new
                        {
                            EventID = 4,
                            Description = "Symphony orchestra live performance",
                            EventDate = new DateTime(2026, 1, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "Classical Evening",
                            LocationID = 4,
                            PerformerID = 4,
                            RatingAverage = 0f,
                            RatingCount = 0,
                            StatusID = 1,
                            TicketsAvailable = 150,
                            TicketsSold = 50,
                            TotalScore = 0
                        });
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Genre", b =>
                {
                    b.Property<int>("GenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreID");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreID = 1,
                            Name = "Rock"
                        },
                        new
                        {
                            GenreID = 2,
                            Name = "Pop"
                        },
                        new
                        {
                            GenreID = 3,
                            Name = "Jazz"
                        },
                        new
                        {
                            GenreID = 4,
                            Name = "Classical"
                        },
                        new
                        {
                            GenreID = 5,
                            Name = "Electronic"
                        },
                        new
                        {
                            GenreID = 6,
                            Name = "Hip-Hop"
                        },
                        new
                        {
                            GenreID = 7,
                            Name = "Metal"
                        },
                        new
                        {
                            GenreID = 8,
                            Name = "Folk"
                        });
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationID");

                    b.HasIndex("CityID");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationID = 1,
                            Address = "Titova 1, Sarajevo",
                            Capacity = 15000,
                            CityID = 1,
                            LocationName = "Arena Sarajevo"
                        },
                        new
                        {
                            LocationID = 2,
                            Address = "Skenderija 3, Sarajevo",
                            Capacity = 5000,
                            CityID = 1,
                            LocationName = "Skenderija Hall"
                        },
                        new
                        {
                            LocationID = 3,
                            Address = "Zetra 10, Sarajevo",
                            Capacity = 12000,
                            CityID = 1,
                            LocationName = "Zetra Olympic Hall"
                        },
                        new
                        {
                            LocationID = 4,
                            Address = "Trg Krajine 5, Banja Luka",
                            Capacity = 8000,
                            CityID = 2,
                            LocationName = "Banja Luka Arena"
                        },
                        new
                        {
                            LocationID = 5,
                            Address = "Stadionska 1, Tuzla",
                            Capacity = 7000,
                            CityID = 3,
                            LocationName = "Tuzla Stadium"
                        },
                        new
                        {
                            LocationID = 6,
                            Address = "Mostarska 15, Mostar",
                            Capacity = 4000,
                            CityID = 4,
                            LocationName = "Mostar Music Hall"
                        },
                        new
                        {
                            LocationID = 7,
                            Address = "Dom Sportova 1, Split",
                            Capacity = 12000,
                            CityID = 7,
                            LocationName = "Split Arena"
                        },
                        new
                        {
                            LocationID = 8,
                            Address = "Avenija Dubrovnik 15, Zagreb",
                            Capacity = 16000,
                            CityID = 8,
                            LocationName = "Zagreb Arena"
                        },
                        new
                        {
                            LocationID = 9,
                            Address = "Trg Republike 2, Podgorica",
                            Capacity = 9000,
                            CityID = 9,
                            LocationName = "Podgorica Sports Center"
                        },
                        new
                        {
                            LocationID = 10,
                            Address = "Ušće 5, Beograd",
                            Capacity = 18000,
                            CityID = 10,
                            LocationName = "Belgrade Arena"
                        });
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<bool>("isRead")
                        .HasColumnType("bit");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            NotificationID = 1,
                            CreatedAt = new DateTime(2025, 10, 29, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "New performer request waiting for verification!",
                            UserID = 1,
                            isRead = true
                        },
                        new
                        {
                            NotificationID = 2,
                            CreatedAt = new DateTime(2025, 10, 29, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Message = "You have some events waiting for approval!",
                            UserID = 1,
                            isRead = true
                        },
                        new
                        {
                            NotificationID = 3,
                            CreatedAt = new DateTime(2025, 11, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Ilma Karahmet added a new event!",
                            UserID = 7,
                            isRead = false
                        },
                        new
                        {
                            NotificationID = 4,
                            CreatedAt = new DateTime(2025, 10, 28, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Toni Cetinski added a new event!",
                            UserID = 9,
                            isRead = true
                        },
                        new
                        {
                            NotificationID = 5,
                            CreatedAt = new DateTime(2025, 12, 31, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Your event has been approved!",
                            UserID = 4,
                            isRead = false
                        },
                        new
                        {
                            NotificationID = 6,
                            CreatedAt = new DateTime(2025, 1, 22, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Your event has been rejected!",
                            UserID = 5,
                            isRead = false
                        },
                        new
                        {
                            NotificationID = 7,
                            CreatedAt = new DateTime(2025, 2, 9, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Your event has been rejected!",
                            UserID = 3,
                            isRead = false
                        });
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Performer", b =>
                {
                    b.Property<int>("PerformerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerformerID"));

                    b.Property<string>("ArtistName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PerformerID");

                    b.HasIndex("UserID");

                    b.ToTable("Performers");

                    b.HasData(
                        new
                        {
                            PerformerID = 1,
                            ArtistName = "Dzejlica",
                            Bio = "Pop singer from BiH",
                            IsApproved = true,
                            UserID = 2
                        },
                        new
                        {
                            PerformerID = 2,
                            ArtistName = "Ilmica",
                            Bio = "Rising pop artist",
                            IsApproved = true,
                            UserID = 3
                        },
                        new
                        {
                            PerformerID = 3,
                            ArtistName = "Jelena R",
                            Bio = "Famous Croatian pop singer",
                            IsApproved = true,
                            UserID = 4
                        },
                        new
                        {
                            PerformerID = 4,
                            ArtistName = "Toni",
                            Bio = "Popular Croatian pop singer",
                            IsApproved = true,
                            UserID = 5
                        },
                        new
                        {
                            PerformerID = 5,
                            ArtistName = "Zeljko",
                            Bio = "Serbian pop-folk singer",
                            IsApproved = true,
                            UserID = 6
                        });
                });

            modelBuilder.Entity("MyStagePass.Services.Database.PerformerGenre", b =>
                {
                    b.Property<int>("PerformerGenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerformerGenreID"));

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.Property<int>("PerformerID")
                        .HasColumnType("int");

                    b.HasKey("PerformerGenreID");

                    b.HasIndex("GenreID");

                    b.HasIndex("PerformerID", "GenreID")
                        .IsUnique();

                    b.ToTable("PerformerGenre");

                    b.HasData(
                        new
                        {
                            PerformerGenreID = 1,
                            GenreID = 2,
                            PerformerID = 1
                        },
                        new
                        {
                            PerformerGenreID = 21,
                            GenreID = 3,
                            PerformerID = 1
                        },
                        new
                        {
                            PerformerGenreID = 13,
                            GenreID = 8,
                            PerformerID = 1
                        },
                        new
                        {
                            PerformerGenreID = 4,
                            GenreID = 2,
                            PerformerID = 2
                        },
                        new
                        {
                            PerformerGenreID = 5,
                            GenreID = 8,
                            PerformerID = 2
                        },
                        new
                        {
                            PerformerGenreID = 6,
                            GenreID = 2,
                            PerformerID = 3
                        },
                        new
                        {
                            PerformerGenreID = 7,
                            GenreID = 5,
                            PerformerID = 3
                        },
                        new
                        {
                            PerformerGenreID = 8,
                            GenreID = 2,
                            PerformerID = 4
                        },
                        new
                        {
                            PerformerGenreID = 9,
                            GenreID = 1,
                            PerformerID = 4
                        },
                        new
                        {
                            PerformerGenreID = 10,
                            GenreID = 8,
                            PerformerID = 5
                        });
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Purchase", b =>
                {
                    b.Property<int>("PurchaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PurchaseID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            PurchaseID = 1,
                            CustomerID = 1,
                            PurchaseDate = new DateTime(2025, 10, 27, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseID = 2,
                            CustomerID = 2,
                            PurchaseDate = new DateTime(2025, 10, 28, 15, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<int>("RatingValue")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("EventID", "CustomerID")
                        .IsUnique();

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            ReviewID = 1,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerID = 1,
                            EventID = 1,
                            RatingValue = 5
                        },
                        new
                        {
                            ReviewID = 2,
                            CreatedAt = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerID = 1,
                            EventID = 2,
                            RatingValue = 4
                        },
                        new
                        {
                            ReviewID = 3,
                            CreatedAt = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerID = 2,
                            EventID = 1,
                            RatingValue = 3
                        },
                        new
                        {
                            ReviewID = 4,
                            CreatedAt = new DateTime(2025, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerID = 2,
                            EventID = 3,
                            RatingValue = 5
                        },
                        new
                        {
                            ReviewID = 5,
                            CreatedAt = new DateTime(2025, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerID = 3,
                            EventID = 2,
                            RatingValue = 4
                        },
                        new
                        {
                            ReviewID = 6,
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerID = 3,
                            EventID = 3,
                            RatingValue = 2
                        });
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Status", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusID");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusID = 1,
                            StatusName = "Upcoming"
                        },
                        new
                        {
                            StatusID = 2,
                            StatusName = "Ended"
                        },
                        new
                        {
                            StatusID = 3,
                            StatusName = "Pending"
                        },
                        new
                        {
                            StatusID = 4,
                            StatusName = "Approved"
                        },
                        new
                        {
                            StatusID = 5,
                            StatusName = "Rejected"
                        });
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Ticket", b =>
                {
                    b.Property<int>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketID"));

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("PurchaseID")
                        .HasColumnType("int");

                    b.Property<byte[]>("QRCodeData")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("TicketTypeID")
                        .HasColumnType("int");

                    b.HasKey("TicketID");

                    b.HasIndex("EventID");

                    b.HasIndex("PurchaseID");

                    b.HasIndex("TicketTypeID");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketID = 1,
                            EventID = 1,
                            Price = 50f,
                            PurchaseID = 1,
                            TicketTypeID = 1
                        },
                        new
                        {
                            TicketID = 2,
                            EventID = 2,
                            Price = 30f,
                            PurchaseID = 1,
                            TicketTypeID = 2
                        },
                        new
                        {
                            TicketID = 3,
                            EventID = 3,
                            Price = 60f,
                            PurchaseID = 2,
                            TicketTypeID = 1
                        },
                        new
                        {
                            TicketID = 4,
                            EventID = 1,
                            Price = 40f,
                            PurchaseID = 2,
                            TicketTypeID = 3
                        });
                });

            modelBuilder.Entity("MyStagePass.Services.Database.TicketType", b =>
                {
                    b.Property<int>("TicketTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketTypeID"));

                    b.Property<string>("TicketTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TicketTypeID");

                    b.ToTable("TicketTypes");

                    b.HasData(
                        new
                        {
                            TicketTypeID = 1,
                            TicketTypeName = "Regular"
                        },
                        new
                        {
                            TicketTypeID = 2,
                            TicketTypeName = "VIP"
                        },
                        new
                        {
                            TicketTypeID = 3,
                            TicketTypeName = "Premium"
                        });
                });

            modelBuilder.Entity("MyStagePass.Services.Database.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            Image = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 4, 0, 0, 0, 181, 28, 12, 2, 0, 0, 0, 11, 73, 68, 65, 84, 120, 218, 99, 252, 255, 2, 0, 2, 5, 1, 0, 239, 159, 224, 185, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            IsActive = true,
                            LastName = "User",
                            Password = "hashed_password",
                            PhoneNumber = "000000000",
                            Salt = "salt",
                            Username = "admin"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "dzejla@example.com",
                            FirstName = "Dzejla",
                            Image = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 4, 0, 0, 0, 181, 28, 12, 2, 0, 0, 0, 11, 73, 68, 65, 84, 120, 218, 99, 252, 255, 2, 0, 2, 5, 1, 0, 239, 159, 224, 185, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            IsActive = true,
                            LastName = "Ramovic",
                            Password = "hashed_password",
                            PhoneNumber = "111222333",
                            Salt = "salt",
                            Username = "dzejla"
                        },
                        new
                        {
                            UserID = 3,
                            Email = "ilma@example.com",
                            FirstName = "Ilma",
                            Image = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 4, 0, 0, 0, 181, 28, 12, 2, 0, 0, 0, 11, 73, 68, 65, 84, 120, 218, 99, 252, 255, 2, 0, 2, 5, 1, 0, 239, 159, 224, 185, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            IsActive = true,
                            LastName = "Karahmet",
                            Password = "hashed_password",
                            PhoneNumber = "222333444",
                            Salt = "salt",
                            Username = "ilma"
                        },
                        new
                        {
                            UserID = 4,
                            Email = "jelena@example.com",
                            FirstName = "Jelena",
                            Image = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 4, 0, 0, 0, 181, 28, 12, 2, 0, 0, 0, 11, 73, 68, 65, 84, 120, 218, 99, 252, 255, 2, 0, 2, 5, 1, 0, 239, 159, 224, 185, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            IsActive = true,
                            LastName = "Rozga",
                            Password = "hashed_password",
                            PhoneNumber = "333444555",
                            Salt = "salt",
                            Username = "jelena"
                        },
                        new
                        {
                            UserID = 5,
                            Email = "toni@example.com",
                            FirstName = "Toni",
                            Image = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 4, 0, 0, 0, 181, 28, 12, 2, 0, 0, 0, 11, 73, 68, 65, 84, 120, 218, 99, 252, 255, 2, 0, 2, 5, 1, 0, 239, 159, 224, 185, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            IsActive = true,
                            LastName = "Cetinski",
                            Password = "hashed_password",
                            PhoneNumber = "444555666",
                            Salt = "salt",
                            Username = "toni"
                        },
                        new
                        {
                            UserID = 6,
                            Email = "zeljko@example.com",
                            FirstName = "Zeljko",
                            Image = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 4, 0, 0, 0, 181, 28, 12, 2, 0, 0, 0, 11, 73, 68, 65, 84, 120, 218, 99, 252, 255, 2, 0, 2, 5, 1, 0, 239, 159, 224, 185, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            IsActive = true,
                            LastName = "Samardzic",
                            Password = "hashed_password",
                            PhoneNumber = "555666777",
                            Salt = "salt",
                            Username = "zeljko"
                        },
                        new
                        {
                            UserID = 7,
                            Email = "selma@example.com",
                            FirstName = "Selma",
                            Image = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 4, 0, 0, 0, 181, 28, 12, 2, 0, 0, 0, 11, 73, 68, 65, 84, 120, 218, 99, 252, 255, 2, 0, 2, 5, 1, 0, 239, 159, 224, 185, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            IsActive = true,
                            LastName = "Alagic",
                            Password = "hashed_password",
                            PhoneNumber = "666777888",
                            Salt = "salt",
                            Username = "selmica"
                        },
                        new
                        {
                            UserID = 8,
                            Email = "eda@example.com",
                            FirstName = "Eda",
                            Image = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 4, 0, 0, 0, 181, 28, 12, 2, 0, 0, 0, 11, 73, 68, 65, 84, 120, 218, 99, 252, 255, 2, 0, 2, 5, 1, 0, 239, 159, 224, 185, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            IsActive = true,
                            LastName = "Erdem",
                            Password = "hashed_password",
                            PhoneNumber = "777888999",
                            Salt = "salt",
                            Username = "eda"
                        },
                        new
                        {
                            UserID = 9,
                            Email = "tesa@example.com",
                            FirstName = "Tesa",
                            Image = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 4, 0, 0, 0, 181, 28, 12, 2, 0, 0, 0, 11, 73, 68, 65, 84, 120, 218, 99, 252, 255, 2, 0, 2, 5, 1, 0, 239, 159, 224, 185, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            IsActive = true,
                            LastName = "Zahirovic",
                            Password = "hashed_password",
                            PhoneNumber = "888999000",
                            Salt = "salt",
                            Username = "tess"
                        });
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Admin", b =>
                {
                    b.HasOne("MyStagePass.Services.Database.User", "User")
                        .WithMany("Admins")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyStagePass.Services.Database.City", b =>
                {
                    b.HasOne("MyStagePass.Services.Database.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Customer", b =>
                {
                    b.HasOne("MyStagePass.Services.Database.User", "User")
                        .WithMany("Customers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyStagePass.Services.Database.CustomerFavoriteEvent", b =>
                {
                    b.HasOne("MyStagePass.Services.Database.Customer", null)
                        .WithMany("FavoriteEvents")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyStagePass.Services.Database.Event", null)
                        .WithMany("FavoritedByCustomers")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Event", b =>
                {
                    b.HasOne("MyStagePass.Services.Database.Location", "Location")
                        .WithMany("Events")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyStagePass.Services.Database.Performer", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyStagePass.Services.Database.Status", "Status")
                        .WithMany("Events")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Performer");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Location", b =>
                {
                    b.HasOne("MyStagePass.Services.Database.City", "City")
                        .WithMany("Locations")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Notification", b =>
                {
                    b.HasOne("MyStagePass.Services.Database.User", null)
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Performer", b =>
                {
                    b.HasOne("MyStagePass.Services.Database.User", "User")
                        .WithMany("Performers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyStagePass.Services.Database.PerformerGenre", b =>
                {
                    b.HasOne("MyStagePass.Services.Database.Genre", "Genre")
                        .WithMany("Performers")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("MyStagePass.Services.Database.Performer", "Performer")
                        .WithMany("Genres")
                        .HasForeignKey("PerformerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Performer");
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Purchase", b =>
                {
                    b.HasOne("MyStagePass.Services.Database.Customer", null)
                        .WithMany("Purchases")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Review", b =>
                {
                    b.HasOne("MyStagePass.Services.Database.Customer", null)
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("MyStagePass.Services.Database.Event", null)
                        .WithMany("Reviews")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Ticket", b =>
                {
                    b.HasOne("MyStagePass.Services.Database.Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("MyStagePass.Services.Database.Purchase", "Purchase")
                        .WithMany("Tickets")
                        .HasForeignKey("PurchaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyStagePass.Services.Database.TicketType", "TicketType")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Purchase");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("MyStagePass.Services.Database.City", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Customer", b =>
                {
                    b.Navigation("FavoriteEvents");

                    b.Navigation("Purchases");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Event", b =>
                {
                    b.Navigation("FavoritedByCustomers");

                    b.Navigation("Reviews");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Genre", b =>
                {
                    b.Navigation("Performers");
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Location", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Performer", b =>
                {
                    b.Navigation("Genres");
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Purchase", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("MyStagePass.Services.Database.Status", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("MyStagePass.Services.Database.TicketType", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("MyStagePass.Services.Database.User", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Customers");

                    b.Navigation("Notifications");

                    b.Navigation("Performers");
                });
#pragma warning restore 612, 618
        }
    }
}
